// src/lib/constants.ts

import type { Service, Location, Testimonial } from '@/types'

export const COMPANY = {
  name: '3M OURCAR',
  tagline1: 'Tint Your Car While You Shop!',
  tagline2: 'Tint Your Car in 55 Minutes!',
  since: 2006,
  // Head office main numbers (Mirdif City Centre)
  phone: '+971 4 328 9349',
  whatsapp: '971528890119',           // digits only for wa.me links
  whatsappDisplay: '+971 52 889 0119',
  email: 'info@3mourcar.com',
  instagram: 'https://instagram.com/3mourcar',
  facebook: 'https://facebook.com/3mourcar',
  tiktok: 'https://tiktok.com/@3mourcar',
}

export const MALL_LOCATIONS: Location[] = [
  {
    name: 'Mirdif City Centre',
    nameAr: 'مردف سيتي سنتر',
    city: 'Dubai',
    cityAr: 'دبي',
    area: 'Mirdif',
    areaAr: 'مردف',
    parking: 'Inside North West Parking, Level 1, Area A-02',
    parkingAr: 'داخل موقف الشمال الغربي، الطابق الأول، المنطقة A-02',
    hours: '9:00 AM – 10:00 PM',
    hoursAr: '٩:٠٠ ص – ١٠:٠٠ م',
    phone: '+971 4 328 9349',
    mobile: '+971 52 889 0119',
    mobile2: '+971 55 381 6059',
    whatsapp: '971528890119',
    whatsappDisplay: '+971 52 889 0119',
    mapUrl: 'https://maps.app.goo.gl/sUPBoVgGouAQDyyEA',
    isHeadOffice: true,
  },
  {
    name: 'Ibn Battuta Mall',
    nameAr: 'مول ابن بطوطة',
    city: 'Dubai',
    cityAr: 'دبي',
    area: 'Jebel Ali',
    areaAr: 'جبل علي',
    parking: 'Parking No. 6, Near China Court',
    parkingAr: 'موقف رقم 6، بالقرب من الساحة الصينية',
    hours: '9:00 AM – 10:00 PM',
    hoursAr: '٩:٠٠ ص – ١٠:٠٠ م',
    phone: '+971 4 366 9392',
    fax: '+971 4 366 9391',
    mobile: '+971 50 899 7412',
    whatsapp: '971508997412',
    whatsappDisplay: '+971 50 899 7412',
    mapUrl: 'https://maps.app.goo.gl/qGR4hgvvkLPxJhQM9',
  },
  {
    name: 'Mall of the Emirates',
    nameAr: 'مول الإمارات',
    city: 'Dubai',
    cityAr: 'دبي',
    area: 'Al Barsha',
    areaAr: 'البرشاء',
    parking: 'Level 2, Sky Dubai Side, Row A1, Orange Colour Parking',
    parkingAr: 'الطابق الثاني، جهة سكاي دبي، صف A1، موقف اللون البرتقالي',
    hours: '9:00 AM – 10:00 PM',
    hoursAr: '٩:٠٠ ص – ١٠:٠٠ م',
    phone: '+971 4 340 4043',
    mobile: '+971 55 752 7622',
    whatsapp: '971557527622',
    whatsappDisplay: '+971 55 752 7622',
    mapUrl: 'https://maps.google.com/?q=Mall+of+the+Emirates+Dubai',
  },
  {
    name: 'Dubai Mall',
    nameAr: 'دبي مول',
    city: 'Dubai',
    cityAr: 'دبي',
    area: 'Downtown Dubai',
    areaAr: 'وسط مدينة دبي',
    parking: 'Level 3, Cinema Parking No. 3, Row E & F',
    parkingAr: 'الطابق الثالث، موقف السينما رقم 3، الصف E و F',
    hours: '9:00 AM – 10:00 PM',
    hoursAr: '٩:٠٠ ص – ١٠:٠٠ م',
    phone: '+971 50 920 7686',
    mobile: '+971 55 574 1920',
    whatsapp: '971555741920',
    whatsappDisplay: '+971 55 574 1920',
    mapUrl: 'https://maps.app.goo.gl/BVgRFTK5vbhuwFgj7',
  },
  {
    name: 'Deira City Centre',
    nameAr: 'ديرة سيتي سنتر',
    city: 'Dubai',
    cityAr: 'دبي',
    area: 'Deira',
    areaAr: 'ديرة',
    parking: 'P3 Ground Floor, Slot Next to E-41',
    parkingAr: 'الطابق الأرضي P3، موقف بجانب E-41',
    hours: '9:00 AM – 10:00 PM',
    hoursAr: '٩:٠٠ ص – ١٠:٠٠ م',
    mobile: '+971 50 503 8385',
    whatsapp: '971505038385',
    whatsappDisplay: '+971 50 503 8385',
    mapUrl: 'https://maps.app.goo.gl/5xnzPDuKZQzzftZe9',
  },
  {
    name: 'BurJuman Mall',
    nameAr: 'مركز برجمان',
    city: 'Dubai',
    cityAr: 'دبي',
    area: 'Bur Dubai',
    areaAr: 'بر دبي',
    parking: 'Carrefour Parking, Ground Floor, Lobby D, Row 29',
    parkingAr: 'موقف كارفور، الطابق الأرضي، اللوبي D، الصف 29',
    hours: '9:00 AM – 10:00 PM',
    hoursAr: '٩:٠٠ ص – ١٠:٠٠ م',
    phone: '+971 4 386 4030',
    mobile: '+971 55 573 6105',
    whatsapp: '971555736105',
    whatsappDisplay: '+971 55 573 6105',
    mapUrl: 'https://maps.app.goo.gl/f1Eya6GCJYWwXx2H8',
  },
  {
    name: 'Circle Mall JVC',
    nameAr: 'سيركل مول JVC',
    city: 'Dubai',
    cityAr: 'دبي',
    area: 'Jumeirah Village Circle',
    areaAr: 'قرية جميرا الدائرية',
    parking: 'Basement 1 Parking, Slots 123–125',
    parkingAr: 'موقف البدروم 1، أماكن 123–125',
    hours: '9:00 AM – 10:00 PM',
    hoursAr: '٩:٠٠ ص – ١٠:٠٠ م',
    mobile: '+971 50 899 7405',
    whatsapp: '971508997405',
    whatsappDisplay: '+971 50 899 7405',
    mapUrl: 'https://maps.app.goo.gl/WCp4bdoVzwacZMDP8',
  },
  {
    name: 'Dubai Marina Mall',
    nameAr: 'دبي مارينا مول',
    city: 'Dubai',
    cityAr: 'دبي',
    area: 'Dubai Marina',
    areaAr: 'دبي مارينا',
    parking: 'Lower Car Park P2, Parking Row P2 E',
    parkingAr: 'موقف السيارات السفلي P2، الصف P2 E',
    hours: '9:00 AM – 10:00 PM',
    hoursAr: '٩:٠٠ ص – ١٠:٠٠ م',
    mobile: '+971 56 404 0584',
    whatsapp: '971564040584',
    whatsappDisplay: '+971 56 404 0584',
    mapUrl: 'https://maps.app.goo.gl/N7k79B1NLCQLceQF7',
  },
  {
    name: 'Al Wahda Mall',
    nameAr: 'مول الوحدة',
    city: 'Abu Dhabi',
    cityAr: 'أبوظبي',
    area: 'Al Wahda',
    areaAr: 'الوحدة',
    parking: 'Mall Extension, Basement No. 1, Parking No. 4',
    parkingAr: 'امتداد المول، البدروم رقم 1، موقف رقم 4',
    hours: '9:00 AM – 10:00 PM',
    hoursAr: '٩:٠٠ ص – ١٠:٠٠ م',
    phone: '+971 2 666 4595',
    mobile: '+971 55 324 0687',
    whatsapp: '971553240687',
    whatsappDisplay: '+971 55 324 0687',
    mapUrl: 'https://maps.app.goo.gl/6x97Y7MAXiyKS5zZ6',
  },
]

export const AUTOMOTIVE_SERVICES: Service[] = [
  {
    slug: 'window-tinting',
    title: '3M Window Tinting',
    shortTitle: 'Window Tinting',
    category: 'automotive',
    description: 'Premium 3M window films offering superior heat rejection, UV protection and privacy for your vehicle.',
    icon: '🪟',
    heroImage: '/images/services/window-tinting-hero.jpg',
    benefits: [
      { icon: '🌡️', title: 'Heat Rejection', description: 'Block up to 60% of solar heat for a cooler cabin and reduced AC load.' },
      { icon: '🔆', title: 'UV Protection', description: 'Block 99% of harmful UV rays — protecting you and your interior.' },
      { icon: '👁️', title: 'Glare Reduction', description: 'Eliminate sun and headlight glare for safer, more comfortable driving.' },
      { icon: '🔒', title: 'Privacy', description: 'Enhanced privacy while maintaining clear outward visibility.' },
      { icon: '🎨', title: 'Premium Aesthetics', description: 'Sleek professional look that enhances your vehicle\'s appearance.' },
      { icon: '📅', title: 'Lifetime Warranty', description: 'Backed by 3M\'s manufacturer warranty for peace of mind.' },
    ],
    features: ['3M Crystalline Series', '3M Ceramic IR Series', '3M FX Series', 'Multiple VLT Options', 'Certified Installation'],
  },
  {
    slug: 'ppf',
    title: 'Paint Protection Film (PPF)',
    shortTitle: 'PPF',
    category: 'automotive',
    description: 'Invisible 3M Scotchgard Paint Protection Film that shields your paint from stone chips, scratches and environmental damage.',
    icon: '🛡️',
    heroImage: '/images/services/ppf-hero.jpg',
    benefits: [
      { icon: '🛡️', title: 'Stone Chip Guard', description: 'Protect paint from gravel, stone chips and road debris at speed.' },
      { icon: '🔧', title: 'Self-Healing', description: 'Minor scratches disappear in heat — the film heals itself.' },
      { icon: '💧', title: 'Hydrophobic', description: 'Water-beading surface repels dirt, bugs and environmental contaminants.' },
      { icon: '🎨', title: 'Paint Preservation', description: 'Maintain original paint value and showroom finish for resale.' },
      { icon: '⚡', title: 'Optical Clarity', description: 'Completely invisible — preserves your vehicle\'s colour and gloss.' },
      { icon: '📅', title: 'Long Warranty', description: 'Multi-year manufacturer warranty on genuine 3M Scotchgard film.' },
    ],
    features: ['3M Scotchgard Pro Series', 'Full Car Coverage', 'Partial / High-Impact Zones', 'Self-Healing Technology', 'Paint Safe Installation'],
  },
  {
    slug: 'ceramic-coating',
    title: 'Ceramic Coating',
    shortTitle: 'Ceramic Coating',
    category: 'automotive',
    description: 'Professional nano-ceramic coating delivering unmatched gloss, hydrophobic protection and long-lasting paint defence.',
    icon: '✨',
    heroImage: '/images/services/ceramic-hero.jpg',
    benefits: [
      { icon: '✨', title: '9H Hardness', description: 'Diamond-hard nano-ceramic layer bonded permanently to your paint.' },
      { icon: '💧', title: 'Hydrophobic', description: 'Water, mud and contaminants bead and roll off effortlessly.' },
      { icon: '🌟', title: 'Deep Gloss', description: 'Amplifies paint depth and metallic flake reflection dramatically.' },
      { icon: '🧹', title: 'Easy Cleaning', description: 'Self-cleaning properties keep your car cleaner, longer.' },
      { icon: '🔆', title: 'UV Resistance', description: 'Prevents paint oxidation and UV-induced colour fade over years.' },
      { icon: '📅', title: 'Long Lasting', description: 'Years of protection from a single professional application.' },
    ],
    features: ['9H Ceramic Grade', 'Multi-Layer Packages', 'Paint Correction Prep', 'Hydrophobic Surface', 'UV & Chemical Resistance'],
  },
  {
    slug: 'car-polishing',
    title: 'Car Polishing',
    shortTitle: 'Car Polishing',
    category: 'automotive',
    description: 'Professional multi-stage paint correction and machine polishing to restore and enhance your paint to showroom condition.',
    icon: '💎',
    heroImage: '/images/services/polishing-hero.jpg',
    benefits: [
      { icon: '💎', title: 'Swirl Removal', description: 'Eliminate spider web swirl marks caused by car washes.' },
      { icon: '🔧', title: 'Scratch Correction', description: 'Remove fine scratches and buffer marks from paintwork.' },
      { icon: '🌟', title: 'Paint Restoration', description: 'Restore faded, oxidised paint back to vibrant original colour.' },
      { icon: '✨', title: 'Showroom Shine', description: 'Machine polished to a mirror-like, deep-gloss finish.' },
      { icon: '📏', title: 'Paint Safe Process', description: 'Paint depth measured before and after — zero risk method.' },
      { icon: '🎨', title: 'Pre-Coat Prep', description: 'Ideal preparation step before ceramic coating application.' },
    ],
    features: ['1-Step, 2-Step & 3-Step Correction', 'Paint Thickness Measurement', 'Machine Polish', 'DA & Rotary Polishing', 'Swirl & Scratch Removal'],
  },
  {
    slug: 'car-detailing',
    title: 'Car Detailing',
    shortTitle: 'Car Detailing',
    category: 'automotive',
    description: 'Complete interior and exterior detailing packages to bring your vehicle back to pristine, like-new condition.',
    icon: '🚗',
    heroImage: '/images/services/detailing-hero.jpg',
    benefits: [
      { icon: '🚗', title: 'Full Interior', description: 'Vacuum, steam clean, leather conditioning and panel treatment.' },
      { icon: '💧', title: 'Exterior Wash', description: 'Hand wash, clay bar and panel wipe decontamination.' },
      { icon: '👃', title: 'Odor Removal', description: 'Professional odor elimination — not just masking with fragrance.' },
      { icon: '🌿', title: 'Leather Care', description: 'Deep clean and condition all leather and vinyl surfaces.' },
      { icon: '⚡', title: 'Engine Bay', description: 'Safe engine bay cleaning for a like-new underhood appearance.' },
      { icon: '🛡️', title: 'Fabric Protection', description: 'Scotchgard fabric and carpet protection treatment.' },
    ],
    features: ['Interior Deep Clean', 'Exterior Hand Wash', 'Clay Bar Treatment', 'Leather Conditioning', 'Engine Bay Detail', 'Fabric Protection'],
  },
]

export const RESIDENTIAL_SERVICES: Service[] = [
  {
    slug: 'sun-control',
    title: '3M Sun Control Window Films',
    shortTitle: 'Sun Control',
    category: 'residential',
    description: 'Reduce heat and glare while maintaining natural light — cutting energy bills and protecting interiors.',
    icon: '☀️',
    heroImage: '/images/services/sun-control-hero.jpg',
    benefits: [
      { icon: '🌡️', title: 'Heat Reduction', description: 'Reject up to 78% of solar heat entering through windows.' },
      { icon: '🔆', title: 'Glare Control', description: 'Reduce glare by up to 89% without darkening your space.' },
      { icon: '💰', title: 'Energy Savings', description: 'Lower cooling costs significantly — measurable ROI.' },
      { icon: '🔆', title: 'UV Block', description: 'Block 99% of UV rays protecting furniture, art and flooring.' },
      { icon: '🎨', title: 'Aesthetics', description: 'Maintain clear views and natural light with minimal visible tint.' },
      { icon: '🏠', title: 'All Properties', description: 'Suitable for homes, apartments, offices and retail spaces.' },
    ],
    features: ['3M Sun Control Range', 'Multiple Tint Levels', 'Exterior & Interior Films', 'Low-E Options', 'Scratch Resistant Coating'],
  },
  {
    slug: 'safety-security',
    title: '3M Safety & Security Window Films',
    shortTitle: 'Safety & Security',
    category: 'residential',
    description: 'Micro-layered safety films that hold shattered glass together — protecting people and property.',
    icon: '🔒',
    heroImage: '/images/services/safety-hero.jpg',
    benefits: [
      { icon: '🔒', title: 'Shatter Resistance', description: 'Holds broken glass fragments together on impact.' },
      { icon: '🛡️', title: 'Break-In Deterrent', description: 'Delays forced entry significantly — thieves move on.' },
      { icon: '💨', title: 'Blast Mitigation', description: 'Reduces injury risk from blast pressure waves.' },
      { icon: '👶', title: 'Child Safety', description: 'Protects children from accidental glass breakage injuries.' },
      { icon: '🌪️', title: 'Storm Protection', description: 'Helps windows withstand extreme weather and debris.' },
      { icon: '✅', title: 'Compliance', description: 'Meets international safety glazing standards.' },
    ],
    features: ['3M Safety Series', 'Multiple Thickness Options', 'Clear & Tinted Variants', 'Attachment System', 'Bomb Blast Rated Options'],
  },
  {
    slug: 'decorative',
    title: '3M Decorative Window Films',
    shortTitle: 'Decorative Films',
    category: 'residential',
    description: 'Frosted, patterned and branded window films for privacy, aesthetics and custom branding.',
    icon: '🎨',
    heroImage: '/images/services/decorative-hero.jpg',
    benefits: [
      { icon: '🔍', title: 'Privacy', description: 'Frosted and opaque options for offices, bathrooms and partitions.' },
      { icon: '🎨', title: 'Design Freedom', description: 'Custom patterns, logos and graphics on glass surfaces.' },
      { icon: '💡', title: 'Light Diffusion', description: 'Maintain natural light while adding privacy and style.' },
      { icon: '🏢', title: 'Branding', description: 'Brand your office glass with custom cut vinyl and film.' },
      { icon: '🔧', title: 'Easy Apply', description: 'Professional installation with removable options available.' },
      { icon: '💰', title: 'Cost Effective', description: 'Affordable alternative to sandblasted or etched glass.' },
    ],
    features: ['Frosted Films', 'Patterned Films', 'Custom Print', 'Gradient Options', 'Removable Variants'],
  },
]

export const MARINE_SERVICES: Service[] = [
  {
    slug: 'sun-control',
    title: '3M Marine Sun Control Films',
    shortTitle: 'Marine Sun Control',
    category: 'marine',
    description: 'Marine-grade 3M sun control films that dramatically reduce cabin heat and protect vessel interiors.',
    icon: '⛵',
    heroImage: '/images/services/marine-sun-hero.jpg',
    benefits: [
      { icon: '🌡️', title: 'Cabin Cooling', description: 'Dramatically reduce heat build-up inside cabins and wheelhouses.' },
      { icon: '🔆', title: 'UV Protection', description: 'Protect upholstery, dashboards and electronics from UV damage.' },
      { icon: '👁️', title: 'Glare Reduction', description: 'Reduce water glare for safer navigation and comfort.' },
      { icon: '🌊', title: 'Marine Grade', description: 'Engineered to withstand the demanding marine environment.' },
      { icon: '💰', title: 'Interior Preservation', description: 'Extend the life of all interior furnishings and materials.' },
      { icon: '🎨', title: 'Appearance', description: 'Professional finish that enhances your vessel\'s aesthetics.' },
    ],
    features: ['Marine-Grade 3M Film', 'Heat Rejection up to 78%', '99% UV Block', 'Multiple VLT Options', 'Salt Air Resistant'],
  },
  {
    slug: 'safety-security',
    title: '3M Marine Safety & Security Films',
    shortTitle: 'Marine Safety',
    category: 'marine',
    description: 'Enhanced safety films for vessel glass — holding fragments together in case of impact or storm.',
    icon: '🔐',
    heroImage: '/images/services/marine-safety-hero.jpg',
    benefits: [
      { icon: '🔒', title: 'Impact Resistance', description: 'Holds shattered glass together after collision or impact.' },
      { icon: '🌊', title: 'Wave Protection', description: 'Protects against wave impact and storm conditions.' },
      { icon: '👥', title: 'Crew Safety', description: 'Significantly reduces risk of glass injury onboard.' },
      { icon: '🔐', title: 'Security', description: 'Deters break-ins and protects vessel when moored.' },
      { icon: '🌿', title: 'Salt Resistant', description: 'Marine-grade adhesive withstands salt air and humidity.' },
      { icon: '✅', title: 'Marine Standards', description: 'Meets maritime safety glazing requirements.' },
    ],
    features: ['Marine Safety Series', 'Anti-Shatter Protection', 'Salt & Humidity Resistant', 'Clear & Tinted Options', 'Marine-Grade Adhesive'],
  },
]

export const CERTIFICATIONS = [
  { title: '3M Authorized Dealer', subtitle: 'Since 2006', description: 'Official recognition as an authorized dealer of 3M automotive and architectural window films.' },
  { title: 'Installation Certification', subtitle: 'Annually Renewed', description: 'Awarded to technicians who meet 3M\'s rigorous standards for professional film application.' },
  { title: 'Excellence Award', subtitle: 'Multiple Years', description: 'Presented for outstanding performance in window film installation quality and customer satisfaction.' },
  { title: 'Customer Service Award', subtitle: '2023', description: 'Recognized for exceptional client experience and after-service support standards.' },
  { title: 'Industry Recognition', subtitle: '2022 · 2023 · 2024', description: 'Acknowledged by the automotive industry for innovation and professional excellence.' },
]

export const TESTIMONIALS: Testimonial[] = [
  {
    name: 'Ahmed Al Mansouri',
    location: 'Dubai Mall',
    rating: 5,
    text: 'Done in under an hour while I was shopping at Dubai Mall. The tint looks absolutely professional — you can tell it\'s quality 3M film. Highly recommend!',
    service: 'Window Tinting',
  },
  {
    name: 'Asfand',
    location: 'Circle Mall JVC',
    rating: 5,
    text: 'It was a great experience to apply safety and security films for my villa. The team was professional, clean, and the finish looks excellent. Highly recommended.',
    service: 'Safety & Security Film',
  },
  {
    name: 'Gabriel',
    location: 'Circle Mall JVC',
    rating: 5,
    text: 'Great experience installing 3M safety & security film for our home. Clear finish, strong protection, and the installers were on time and very careful with the glass.',
    service: 'Safety & Security Film',
  },
  {
    name: 'Mark',
    location: 'Circle Mall JVC',
    rating: 5,
    text: 'Excellent service from start to finish. We applied safety and security films for our villa windows and the result is almost invisible but feels much safer.',
    service: 'Safety & Security Film',
  },
  {
    name: 'Nadia',
    location: 'Circle Mall JVC',
    rating: 5,
    text: 'Very professional and fast installation. The safety film gives peace of mind and the team explained everything clearly. Clean work and great after-support.',
    service: 'Safety & Security Film',
  },
  {
    name: 'Imran',
    location: 'Circle Mall JVC',
    rating: 5,
    text: 'Booked safety & security film for our villa and the experience was smooth. The crew was respectful, protected the area, and finished with a neat, premium look.',
    service: 'Safety & Security Film',
  },
  {
    name: 'Sara K.',
    location: 'Mall of the Emirates',
    rating: 5,
    text: 'My third car with 3M OURCAR. They\'ve been consistent every single time — same quality, same professionalism. The ceramic coating on my GLE is stunning.',
    service: 'Ceramic Coating',
  },
  {
    name: 'Mohammed R.',
    location: 'BurJuman Mall',
    rating: 5,
    text: 'Got PPF and window tinting done at BurJuman. The team was knowledgeable, quick, and the finish is flawless. Worth every dirham for the 3M quality.',
    service: 'PPF + Window Tinting',
  },
  {
    name: 'Fatima A.',
    location: 'Ibn Battuta Mall',
    rating: 5,
    text: 'My Porsche Cayenne looks brand new after the detailing and polishing. The team took their time and the results speak for themselves. Exceptional service.',
    service: 'Detailing + Polishing',
  },
]
